#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
entity_all_0720_peter 翻译补齐脚本（2026-07-20）
规则（沿用多语言翻译复用检查清单）：
- zh_in_1033：1033 含中文 → 中文写入 2052，1033 改为英文
- miss_2052：1033 为英文且 2052 为空 → 按字典填入 2052 中文
- 仅处理 19 个目标实体行
翻译来源优先级：翻译总表/旧脚本字典 > 本次新翻译字典（按 unmatched.json 索引）
"""
import re, json, sys
import xml.etree.ElementTree as ET

sys.path.insert(0, '/Users/peterqiu/Work/AIWorkSpace/SanYi/.venv_excel/lib/python3.13/site-packages')

NS = {'ss': 'urn:schemas-microsoft-com:office:spreadsheet'}
SS = '{%s}' % NS['ss']

TARGETS = {'mcs_credit_items','mcs_credititem_value','mcs_credit_scoringcard','mcs_credit_record','mcs_customer_tag',
           'mcs_credit','mcs_creditmodelprocess',
           'mcs_coface_nace_mapping','mcs_coface_financial_indicator','mcs_coface_exchange_rate',
           'mcs_trade_pttype','mcs_trade_ptgrouptype','mcs_trade_stpayterm',
           'mcs_fca_mdlconfig','mcs_fca_mdlversion','mcs_fca_proc','mcs_fca_quota','mcs_fca_quotaapp','mcs_fca_records'}

def has_chinese(s):
    return bool(s) and bool(re.search(r'[\u4e00-\u9fff]', s))

# ============ 新翻译字典：zh_in_1033（按 unmatched.json 中 zh 类索引） ============
NEW_EN = {
0: 'Calculation log',
1: 'Model calculation serial number, automatically generated by the system.',
2: 'Model Calculation Serial Number',
3: 'Step 1: credit limit (USD) calculated by the model.',
4: 'Model Calculated Quota',
5: 'Credit rejection scenarios 1/2/3/4',
6: 'Credit Rejected',
7: 'Credit rejection scenarios 1/2/3/4',
8: 'Scenario 1',
9: 'Scenario 2',
10: 'Scenario 3',
11: 'Scenario 4',
12: 'Step 2: initial credit amount (USD) after adjustment.',
13: 'Model Adjusted Quota',
14: '1 Credit Validation / 2 Model Calculation / 3 Activated / 4 Returned for Recalculation',
15: 'Credit Validation',
16: 'Model Calculation',
17: 'Activated',
18: 'Returned for Recalculation',
19: 'Factory Credit Model Version',
20: 'Credit Validation',
21: 'Credit Rejected',
22: 'Record Update Information',
23: 'Model Calculation',
24: 'Model Version and Calculation Log',
25: 'Calculation Log',
26: 'Unique identifier for the Customer Scoring Card Configuration',
27: 'Status of the Customer Scoring Card Configuration',
28: 'Brought in read-only from the Customer Credit Scoring Item based on the selected scoring item code. 1 - Quantitative, 2 - Qualitative',
29: 'Maximum value of the configured range (exclusive: scoring item value < max). Conditionally optional; required for quantitative indicators',
30: 'Code of the scoring item, referenced by program logic. Will be changed to a Lookup associated with mcs_credit_scoringcard later',
31: 'Includes 5 types of customer scoring cards and 2 types of dealer scoring cards',
32: 'Scoring card configuration name',
33: 'Short name of the scoring item, used for credit score display. Auto-populated from the Lookup, read-only',
34: 'Auto-populated from the Lookup, read-only',
35: 'Reason for the status of the Customer Scoring Card Configuration',
36: 'Weighted score given when the scoring item value falls within the range',
37: 'Minimum value of the configured range (inclusive: min <= scoring item value). Conditionally optional; required for quantitative indicators',
38: 'Score Configuration',
39: 'Customer Scoring Card',
40: 'Customer Scoring Card Configuration Advanced Find View',
41: 'Customer Credit Scoring Item Advanced Find View',
42: 'Customer Scoring Card Configuration Associated View',
43: 'Customer Credit Scoring Item Associated View',
44: 'Quick Find Active Customer Credit Scoring Items',
45: 'Customer Scoring Card Configuration Lookup View',
46: 'Customer Credit Scoring Item Lookup View',
47: 'My Customer Credit Scoring Items',
48: 'Active Customer Credit Scoring Items owned by me',
49: 'My Customer Scoring Card Configurations',
50: 'Active Customer Scoring Card Configurations owned by me',
51: '1 Submitted / 2 Under Approval / 3 Approved / 4 Rejected',
52: 'Submitted',
53: 'Under Approval',
54: 'Approved',
55: 'Rejected',
56: 'BPP approval link (aligned with the mcs_credit_record template)',
57: 'Current BPP approver, uniformly written back by the BPP framework (aligned with the mcs_credit_record template)',
58: 'Aggregated from mcs_approvedquota; non-L/C and L/C, can coexist and be combined with commas',
59: 'Credit Insurance Quota Type',
60: 'Same as the contract payment type dictionary',
61: 'Full Payment',
62: 'Credit Sale',
63: 'Letter of Credit',
64: 'Internal Financing',
65: 'External Financing',
66: 'Financial Leasing',
67: 'Bill',
68: 'Installment',
69: 'Channel Financing',
70: 'Dealer Credit Sale',
71: 'Dealer Direct Sale',
72: 'Bidding Settlement',
73: 'Model calculated quota (USD)',
74: 'Product type',
75: 'BPP workflow instance ID, uniformly written back by the BPP framework (aligned with the mcs_credit_record template)',
76: 'Application number',
77: 'Approval Link',
78: 'Intended contract amount',
79: 'Factory Credit Model Calculation',
80: 'General / Intended Contract',
81: 'General / Intended Contract',
82: 'Sinosure Quota Information',
83: 'Current Factory Credit and Intended Transaction Information',
84: 'Adjusted Factory Credit Quota Information',
85: 'Application Organization',
86: 'Attachments',
87: 'Approval (BPP)',
88: 'Approval (BPP)',
89: 'Approval Link',
90: 'Base entity for process Factory Credit Model Calculation Process',
91: 'Factory Credit Model Calculation Processes',
92: 'Status of the Factory Credit Model Calculation Process',
93: 'Reason for the status of the Factory Credit Model Calculation Process',
94: 'Credit Validation',
95: 'Model Calculation',
96: 'Activated',
97: 'Active Factory Credit Model Calculation Processes',
98: 'All Factory Credit Model Calculation Processes',
99: 'Inactive Factory Credit Model Calculation Processes on my Factory Credit Model Calculation List',
100: 'Active Factory Credit Model Calculation Processes on my Factory Credit Model Calculation List',
101: 'Inactive Factory Credit Model Calculation Processes',
102: 'Factory Credit Model Calculation Process Advanced Find View',
103: 'Factory Credit Model Calculation Process Associated View',
104: 'Quick Find Active Factory Credit Model Calculation Processes',
105: 'Factory Credit Model Calculation Process Lookup View',
106: 'All active Factory Credit Model Calculation Processes',
107: 'Factory credit model calculation record',
108: 'Whether the quota is effective, 1 - Yes, 0 - No',
109: 'Quota Information',
110: 'Manually selected; effective by default when a new record is saved. 1 = Yes, 0 = No',
111: 'Whether the model version is effective, 1 - Yes, 0 - No',
112: 'Credit Parameter Configuration',
113: 'Base entity for process Credit Assessment',
114: 'Status of the Credit Assessment',
115: 'Reason for the status of the Credit Assessment',
116: 'Owner',
117: 'Scoring Date',
118: 'Approval Initiated',
119: 'Approval Completed',
120: 'Active Credit Assessments',
121: 'Inactive Credit Assessments',
122: 'All Credit Assessments',
123: 'Inactive Credit Assessments on my Customer Credit Assessment Records',
124: 'Active Credit Assessments on my Customer Credit Assessment Records',
125: 'Credit Assessment Advanced Find View',
126: 'Credit Assessment Associated View',
127: 'Quick Find Active Credit Assessments',
128: 'Credit Assessment Lookup View',
129: 'All active Credit Assessments',
130: 'Coface Financial Indicator Mappings',
131: 'Status of the Coface Financial Indicator Mapping',
132: 'Location where the indicator value is retrieved in the Coface JSON',
133: 'Indicator name: NetAssets / DebtRatio / CurrentRatio / NetProfitMargin',
134: 'Country code, e.g. AR / IN / MY',
135: 'Whether this configuration is effective',
136: 'Matching order when multiple candidate codes exist for the same indicator of the same country; smaller numbers take priority',
137: 'Coface indicator.type.value code, e.g. 21 / 1000 / 4105',
138: 'Formula description used to calculate the indicator when direct retrieval fails',
139: 'Country name, e.g. ARGENTINA',
140: 'Reason for the status of the Coface Financial Indicator Mapping',
141: 'Active Coface Financial Indicator Mappings',
142: 'Active Coface Financial Indicator Mappings owned by me',
143: 'Status of the Qualitative Scoring Item Enum Value',
144: 'Stores raw values returned by the Coface API; multiple values are separated by English commas and used to map to SANY standard codes',
145: 'Coface Raw Value',
146: 'Reason for the status of the Qualitative Scoring Item Enum Value',
147: 'Associated with the Customer Credit Scoring Item',
148: 'Customer Credit Scoring Item',
149: 'Active Qualitative Scoring Item Enum Values',
150: 'Active Qualitative Scoring Item Enum Values owned by me',
151: 'Coface Exchange Rate Configuration',
152: 'Currency code',
153: 'Status of the Coface Exchange Rate Configuration',
154: 'Effective date of the exchange rate record, supporting multiple sets of rates maintained by year',
155: 'Only enabled records participate in exchange rate conversion',
156: 'Currency name in English or Chinese',
157: 'Currency Name',
158: 'Exchange rate source or update notes',
159: 'USD amount per 1 unit of local currency, e.g. CNY=0.1463',
160: 'Exchange Rate to USD',
161: 'Reason for the status of the Coface Exchange Rate Configuration',
162: 'Inactive Coface Exchange Rate Configurations',
163: 'Active Coface Exchange Rate Configurations',
164: 'Coface Exchange Rate Configuration Advanced Find View',
165: 'Coface Exchange Rate Configuration Associated View',
166: 'Quick Find Active Coface Exchange Rate Configurations',
167: 'Coface Exchange Rate Configuration Lookup View',
168: 'My Coface Exchange Rate Configurations',
169: 'Active Coface Exchange Rate Configurations owned by me',
170: 'Trade Payment Terms Baselines',
171: 'Associated with business unit master data',
172: 'Payment term days, 0 or a multiple of 30',
173: 'Payment frequency days, 0 or a multiple of 30',
174: 'Down payment ratio, between 0 and 1, displayed as a percentage',
175: 'Trade Payment Terms Baseline - Inactive',
176: 'Trade Payment Terms Baseline - Pending Approval',
177: 'Trade Payment Terms Baseline - Effective',
178: 'Aggregation method applied to the three model factors: financial capability, historical repayment capability, and historical baseline quota; MAX (take maximum) or MIN (take minimum)',
179: 'Aggregation Method',
180: 'Aggregation method MAX/MIN',
181: 'Customer category. Direct sales customer levels include S, A, B, C, I (S/A/B are key accounts); I is individual customer; C is other general customers. D1-D5 represent dealer customers: D1 - Diamond, D2 - Platinum, D3 - Silver, D4 - Certified, D5 - Intention',
182: 'Customer Category',
183: 'Customer category S/A/B/C/I/D1-D5',
184: 'Unique code generated by the system; unique record code',
185: 'Parameter Code',
186: 'Historical baseline quota. The historical factory credit baseline, updated manually each year and generated by the factory credit model. It is only related to [Customer Category], not [Customer Grade]; [Customer Grade] = ALL can be used. When Customer Grade = ALL, this field is required and must be greater than 1000',
187: 'Historical Baseline Quota USD',
188: 'Associated credit model version',
189: 'Model Version',
190: 'Customer grade. Dictionary: A0, A1, A2, A3, A4, ALL. ALL represents all, used to configure the default coefficient when there is no customer grade and to configure the historical baseline quota. The customer grade standard is A0-A4 (A0 is the highest); if the scoring card has a credit score, it overrides: A0 >= 80, A1 >= 70, A2 >= 60, A3 >= 50, A4 < 50',
191: 'Customer grade A0-A4/ALL',
192: 'Factory Credit Model Version',
193: 'Parameter Management Dimensions',
194: 'Model Coefficients and Aggregation Method',
195: 'Historical Baseline Quota',
196: 'Status of the Customer Credit Scoring Item',
197: 'Reason for the status of the Customer Credit Scoring Item',
198: 'Scoring Items (Customer Credit Basic Indicators)',
199: 'Category and Attributes',
200: 'Active Customer Credit Scoring Items',
201: 'Inactive Customer Credit Scoring Items',
202: 'Effective date of the mapping record, supporting switching between multiple sets of mapping rules',
203: 'Status of the Coface NACE Industry Mapping',
204: 'Only enabled records participate in NACE mapping',
205: 'Chinese or English name of the NACE Division, e.g. Manufacturing',
206: 'Mapping rule description or source',
207: 'Reason for the status of the Coface NACE Industry Mapping',
208: 'NACE Rev.2.1 Division code (first two digits), start value for range matching',
209: 'NACE Rev.2.1 Division code (first two digits), end value for range matching; same as the start value indicates a single Division',
210: 'Active Coface NACE Industry Mappings',
211: 'Active Coface NACE Industry Mappings owned by me',
212: 'BPP approval page link',
213: 'Associated trade payment terms product category',
214: 'Associated product line',
215: 'Process stages 1-12',
216: 'Stage 1',
217: 'Stage 2',
218: 'Stage 3',
219: 'Stage 4',
220: 'Stage 5',
221: 'Stage 6',
222: 'Stage 7',
223: 'Stage 8',
224: 'Stage 9',
225: 'Stage 10',
226: 'Stage 11',
227: 'Stage 12',
228: '1 Initialization / 2 Reservation / 3 Occupation / 4 Release',
229: 'Initialization',
230: 'Reservation',
231: 'Occupation',
232: 'Release',
233: 'Contract',
234: 'Order',
235: 'Ledger Information',
236: 'Quota Adjustment Ledger',
}

# ============ 新翻译字典：miss_2052（按 unmatched.json 中 en 类索引） ============
NEW_ZH = {
0: '厂端授信模型计算表列表',
1: '厂端授信模型计算表',
2: '不予授信客户',
3: '客户名称',
4: 'ColorStrip',
5: '厂端授信额度申请表列表',
6: '厂端授信额度申请表',
7: '支付方式',
8: '厂端授信模型计算表',
9: '业务流程流持续时间',
10: '持续时间',
11: '描述',
12: '名称',
13: '计算日期',
14: '计算状态',
15: '此实体的窗体。',
16: '信息',
17: '厂端授信额度表列表',
18: '客户编码',
19: '厂端授信额度表',
20: '是否生效',
21: '厂端授信模型版本表列表',
22: '厂端授信模型版本表',
23: '信用评估记录',
24: '科法斯客户代码',
25: '此实体的卡片窗体。',
26: 'S',
27: 'A',
28: 'B',
29: 'C',
30: 'I',
31: 'D1',
32: 'D2',
33: 'D3',
34: 'D4',
35: 'D5',
36: 'A0',
37: 'A1',
38: 'A2',
39: 'A3',
40: 'A4',
41: '厂端授信模型配置表列表',
42: '聚合方法',
43: '客户分类',
44: '厂端授信模型配置表',
45: '客户信用等级',
46: '评分项目分类',
47: '外部集成提供',
48: '否',
49: '是',
50: '数据类型',
51: '允许人工补录',
52: '内外部',
53: '上传组件',
54: '产品线',
55: '成交条件产品分类',
56: '成交条件产品分类关系列表',
57: '非活动成交条件产品分类关系',
58: '成交条件产品分类关系高级查找视图',
59: '成交条件产品分类关系关联视图',
60: '快速查找活动成交条件产品分类关系',
61: '成交条件产品分类关系查找视图',
62: '我的成交条件产品分类关系',
63: '我拥有的活动成交条件产品分类关系',
64: '厂端授信额度调整台账列表',
65: '厂端授信额度调整台账',
}

def get_row_values(row, expected_cols=16):
    vals = [None] * expected_cols
    idx = 1
    for cell in row.findall('ss:Cell', NS):
        si = cell.get(SS + 'Index')
        if si:
            idx = int(si)
        data = cell.find('ss:Data', NS)
        if idx <= expected_cols:
            vals[idx - 1] = data.text if data is not None else None
        idx += 1
    return vals

def set_cell_value(row, col_idx, value):
    cells = list(row.findall('ss:Cell', NS))
    current_idx = 1
    target = None
    for cell in cells:
        si = cell.get(SS + 'Index')
        if si:
            current_idx = int(si)
        if current_idx == col_idx:
            target = cell
            break
        current_idx += 1
    if target is None:
        target = ET.Element(SS + 'Cell')
        target.set(SS + 'Index', str(col_idx))
        row.append(target)
    for old in list(target.findall('ss:Data', NS)):
        target.remove(old)
    data = ET.Element(SS + 'Data')
    data.set(SS + 'Type', 'String')
    data.text = value
    target.append(data)

def main():
    # 加载既有资产匹配结果与未匹配清单
    matched = json.load(open('/tmp/matched.json'))       # [{'type','zh','en'}]
    unmatched = json.load(open('/tmp/unmatched.json'))   # [{'type','v1033','v2052',...}]

    # 已匹配字典 zh->en
    ZH_EN = {m['zh']: m['en'] for m in matched if m['type'] == 'zh_in_1033'}

    # 未匹配项建立 (type,v1033,v2052)->索引 映射
    un_idx = {}
    for i, u in enumerate(unmatched):
        # 分类型各自编号：与打印时的索引一致（zh 类 0-236，en 类 0-65）
        pass
    zh_list = [u for u in unmatched if u['type'] == 'zh_in_1033']
    en_list = [u for u in unmatched if u['type'] == 'miss_2052']
    zh_key2idx = {(u['v1033'], u['v2052']): i for i, u in enumerate(zh_list)}
    en_key2idx = {(u['v1033'], u['v2052']): i for i, u in enumerate(en_list)}

    tree = ET.parse('extracted/CrmTranslations.xml')
    root = tree.getroot()
    sheet = root.find('.//ss:Worksheet[@ss:Name="Localized Labels"]', NS)
    table = sheet.find('.//ss:Table', NS)

    stat = {'reused': 0, 'new_en': 0, 'new_zh': 0}
    leftover = []
    changes = []  # (entity, col, old1033, new1033, new2052, source)

    for row in table.findall('ss:Row', NS):
        vals = get_row_values(row)
        ent = vals[0]
        if ent not in TARGETS:
            continue
        v1033, v2052 = vals[3], vals[14]
        col = vals[2] or ''

        if has_chinese(v1033):
            # zh_in_1033：1033 改英文，2052 回填中文
            if v1033 in ZH_EN:
                en, src = ZH_EN[v1033], '总表/旧脚本'
                stat['reused'] += 1
            else:
                i = zh_key2idx.get((v1033, v2052))
                if i is None or i not in NEW_EN:
                    leftover.append(('zh_in_1033未翻译', ent, col, v1033))
                    continue
                en, src = NEW_EN[i], '新翻译'
                stat['new_en'] += 1
            set_cell_value(row, 4, en)
            set_cell_value(row, 15, v1033)
            changes.append((ent, col, v1033, en, v1033, src))
        elif v1033 and not v2052:
            # miss_2052：补中文
            i = en_key2idx.get((v1033, v2052))
            if i is not None and i in NEW_ZH:
                zh = NEW_ZH[i]
                set_cell_value(row, 15, zh)
                stat['new_zh'] += 1
                changes.append((ent, col, v1033, v1033, zh, '新翻译'))
            else:
                leftover.append(('miss_2052未翻译', ent, col, v1033))

    tree.write('extracted/CrmTranslations.xml', encoding='utf-8', xml_declaration=True)

    print(f"复用翻译: {stat['reused']}  新翻英文: {stat['new_en']}  新补中文: {stat['new_zh']}")
    print(f"遗留未处理: {len(leftover)}")
    for l in leftover[:30]:
        print('  ', l)
    json.dump(changes, open('/tmp/changes.json', 'w'), ensure_ascii=False, indent=1)
    print(f"变更明细已写 /tmp/changes.json ({len(changes)} 条)")

if __name__ == '__main__':
    main()
