<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <AssemblyName>SanyD365.Plugins.FinancingManagement</AssemblyName>
    <RootNamespace>SanyD365.Plugins.FinancingManagement</RootNamespace>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>keypair.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.42" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
  </ItemGroup>

</Project>
